-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE, SUM(OS.SALES_AMOUNT * PR.PRICE) AS SALES
FROM OFFLINE_SALE OS INNER JOIN PRODUCT PR
ON OS.PRODUCT_ID = PR.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE
ORDER BY SUM(OS.SALES_AMOUNT * PR.PRICE) DESC, PR.PRODUCT_CODE;